---
name: WWW-Splunk
version: 1.11
author:
  - 'Lubomir Rintel <lkundrak@v3.sk>'
abstract: Client library for Splunk log search engine
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  XML::LibXML: 0
requires:
  Carp: 0
  Date::Manip: 0
  Getopt::Long: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Pod::Usage: 0
  Test::More: 0
  Text::CSV: 0
  XML::Feed: 0
  XML::LibXML: 0
configure_requires:
  Module::Build: 0.35
provides:
  WWW::Splunk:
    file: lib/WWW/Splunk.pm
    version: 1.03
  WWW::Splunk::API:
    file: lib/WWW/Splunk/API.pm
    version: 1.10
  WWW::Splunk::XMLParser:
    file: lib/WWW/Splunk/XMLParser.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
